sudo: false
language: node_js
node_js:
  - node
cache: yarn
install:
  - yarn install
script:
  - yarn run build
deploy:
  provider: heroku
  api_key:
    secure: LNKk5S2wIk4jrhxw64DwLbJKVkXkMpov4Aag+czTlhYBfawJsSt58lKGDWT287VJPmYODsoqllCxAm4+AgVeDIdKqTU4GcOW1+d9ilnfo7kN3SO1yuWXPrQ5Zv3gi0C1QWdG/i6qf+h0ELR8FfJhwu9xzto9HidYpUODiIrUN9urD3l6V8fAu82kxIvauqdVu2P5GxDGdlYGW36gD+oWqbStguokqwAnow8ZRrxUJi7uw8Rhr5SvMbZ2m5LlW5r+NbTIW8NI3bkd/F9XpnKiVN0bjaDFvkVlJkBzNM0lti0TCut+/qSHKGYCcDmMu7SqQMoWyqLoDhQxlDM03Z0KN6IQ+hcwmHTy6zasjBcZYPsgzWihSqELgndUy0OBfq3MtpmnmdUOlA7jonlAcMZN3BHvPhPuN9D1jlrmfM9OeAan632oAOJoT707hsmh5v1C0TdIn4XJKG9tKG7kkqJhD4bBghtDSPQpsEBU8+evl4yEavLNwHrtTwgi+mexGrKIO//I/whjgkXn+m+ZUA32vv657tbQ0gUndzTaLhkL1TA4L07/j+/8reo1RXsTscBzrfiOdwWaqe8uBzJ7c9IiJ/1jF2cAP2SlpGrAbhIaDj8gtWzvu++kXuvpjFO5HQwoi6PZ0lUkyVIgh+i78F0d80233g5kdu1b9YOUxltVlyg=
  app: 6f669-1802-454f-17e44675b9
  on:
    repo: salilchhetri/hackernews-react-ssr
