sudo: false
language: node_js
node_js:
  - node
deploy:
  provider: heroku
  api_key:
    secure: H01ilKFDv1NiG7OIchZR3hF8TiDs4VrD1oBMJkQYbk1OTnvQ/FhGAE/NXPuOk0gEwqVH+BTmASg5jmg0TORmlXeG7tbhank7Dr69B4w94qwkMAMMdlrgheI2g4ZZs2+pE1xrDr3OBYR3uDy8IBelfdiFOJAEwwvw1SGtTJydBfucb7NBbC7O2fyI8CC16JioIJuyETzjQRWNbGkjOTbPpqzb2rPZxlzK7NtsB0ieSkjHHFNpuLBUbjsYx/PeOH+MeSd5pEY76oZfSWU93C0QKVYwPYAvkGlJVHeE8CzJa4KHVEUaoc1XY0n+YaP3aWrWFXRCPXeLyne1jH6OLkJVKAbDOsV+g16HFxY3mdFSRoOM0jTjty3Mh7zikgWUaQ9No/FoDdmmmqfIc+EjuIJRBTWRaHlhI+E6Eh8cXVmbniuBn4haw1EKhXkVki9NUHYXsjlb6cerDR8il0C3ZerRtfSAJRZVH/DMclc/PxTPwORggFJHynl40BoAN0pOvYgkJJPgbbCyan5+/iQq1saAcGiQNYWv8+RhGQ04k37TJqI0+i66GttBxEPaCRYd8ITGL6bAVvUMWRWN2P6wAjAdpzjdLJAmNsfRSv2XIgzgX9tuchiVeiRJCAgUzrMl9C2BYv4Y2T5ozc9vMLLJpQQbj1EJ76moqc4vE1afFh8ZlTg=
