sudo: false
language: node_js
node_js:
  - node
cache: yarn
install:
  - yarn install
script:
  - yarn run build
deploy:
  provider: heroku
  api_key:
    secure: quN6lGK5c1M2pV3+/izdJDLpur+hltD9gWGFtDFdmHLquQezy1VEuq1orngOUDcZMWe1OlHjBseUk9jhCCgMTh6xukbRokJst+6vCH8we1pqjX+mQ76lr1HN3YkVq9gMI5bcrT4oLIFIo9KmPPw5H2eLuyX94xvvPvRn1Meyzf5BbZJnNZ+AgOKecPr3YrYyfSoDmqCWJ/VSTxs8ZUUcHc7sICEl+Zw30zWXRIhev1qUj+W0irg4GR8Z8VviaEi86E9avaWMrdQRQSbUsyL7OJl1WS3uWtlvgfFZGTJHbHK7geU4tc9T9LOPg6QKhiSmSUWP1uFMyx7AuCHTouQUl+8uBhPcMUJwJSLvJpXqGgiRI/CDj5RxIJ02Oj0+lUlVd0EF0I4Mb1Fu2lIeispzW0GX+0vvq0bnMxcmxTKFjOfHxrpwi6aBelGBbo3hBy1wTnFCKqwDUH/46lTyGdOqphwPl+yNIXwo7/Jra+NivcenviFCgkoE51wvonyjierqa1oEdG4LwlAMXyTNfP7/7+Qs5Q46C4Sqxb2b98B5zP9Y/CY4/Z7dbkQwozBW7wnPOxa3pGOVHpWGy65E1BgR/NSf1V+aGXc3npYX/FbFfrrMn+KW7+RTA+6WkQM8vEQuLf4PNYucnSyFDBpJJso768SdXDZ6g0an0ucqLW7c9sw=
  app: 9-1802-459a4f-17e44675
  on:
    repo: salilchhetri/hackernews-react-ssr
