sudo: false
language: node_js
node_js:
  - node
cache: yarn
install:
  - yarn install
script:
  - yarn run build
before_deploy: "echo 'ready?'"
deploy:
  provider: heroku
  api_key:
    secure: wDkYoZYEpRl7orGRnz5yhaYoVsrJO1iaA1YqW0HG20sBIs4/maK7se5+Mg73COLzUwjF8+FT+P0X2Iv3thgwvK1iNmiWUpHge/hRDPFZLcner1fMZpkCAjPby1uh2A7hxz4LIe3tWKI9qXnwfjRb7L5/QZfG+begQ9Bhof6+1DOVhqJzfrmX5gEiTdJ1uj4MqWEPOTiW/btqHgQTlLZuEAqMRUkbPcJWM47nzS5RJv3msSBCk/6IxpYmJgyIGvufs1l1K30Ei8JiyNlLVwobzlchRfipyihqkqvO8VzazRZAafvC9pfwXnZbzSP+bUWnkEGF/sUxhWDZSCMoVaK+dTCAmQ4d/7AlVCmQE5LMxdR+Aldy9OfdgyI0tOiLe5BKkD6m99f4IdeOYzJvLaxz85MIOzxyNlabpC/6GuupBIqS214GtP9Bw/3JwrCw7bFEdILFvwNQBouwxQcBnxUj+jwE7O6Acim5m9UNgfUmgVIsk1fp9xbq1rRyWV6R9/0eiPfPYkY34FJlVjHl1LQA1Fpb3iJYtRuQ+fqpqJ8vZL7A617LyHxMcBhwFyOH6PeMPV5WBozi7LjrjYgq2sRgzERuRlMf5U8f7lBG3VEVcqtHgDBHjmnNeZlcntMhL/jI4G4hWHARyhebZYHdTnMZKX+xELtSFukgF0/biAhKfnw=
  on: master
