sudo: false
language: node_js
node_js:
- node
cache: yarn
install:
- yarn install
script:
- yarn run build
deploy:
  provider: heroku
  api_key:
    secure: XMrNt4qk7OU+5umwrpHKTU38gwa/BtmPS4b7M+VwW/i/jD+Kk/CFGGeakNfPkxQT9NpYtntej+e1t7jy6S9l7sVe1xXSMamdZ1U0HU7RmNtHaPYJV5DS1Q30yl2UIS5nL9e0nXWeuQb4LrgdFOIxk9XOd6ihDH50oZSDMwidgHXDt0RgH8AVC2YD/wf2OYRwgheD43oS1dFSBo0viSP2diPvT6NbdxIpHrIO+7v8T2nrBKGjvuPQq2p6F9g1o+D9BsLuTW9Ha7y7UHsGuO5IMqJPK3rqw50vP1mQE/b8RA49qd0lvNGRybSnqJTkUzfyUXrhYWsLcT6D4egfGEKDAH8o2lOn6GuUQpHbwcY+0x0inUCh7HiHwLwFVgVJhKS0LENaqetIgtb5QlEL68irWrbebiX8NhSwKSU/OGF3lSRtPTB+LrcDxJLeQeTP8DWqnFdmF1uR1y9DXsuuVm/hHmM3daxdXr63r3fUtIcfUXJFaLni0ALxBZgZ4wf2TRneAoTJbk8Ycq57P2G6YtwOBwSOhVgG7ufkUQdCRuKqjf17enKoUwJ/0R4+3br3tR/I0Hmb//xLiPeoOXRDpbQN0Rm5RQgYF30klSeiqAKEOqxXtXAveKli/cT6IFZ16yWQ9Jy/P4DKr2jsYEv89aizztvjSsUcKwAyFYGTT9Y0KTM=
  app: 69-1802-454f-17e44675
  on:
    repo: salilchhetri/hackernews-react-ssr
