sudo: false

language: node_js

node_js:
  - node

before_script:
  - npm install

script:
  - npm test
  - npm build

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app:
    master: hackernoon-react-ssr
  on: master
