sudo: false
language: node_js
node_js:
  - node
cache: yarn
install:
  - yarn install
script:
  - yarn run build
deploy:
  provider: heroku
  api_key:
    secure: w7VnwJL1zPcA43DlQ4MLspjDdGwhjPDFYipDupSTA2JL+TY2jx1P5duxcpQ/NiiVhzuTg/JxBxV3q9CdW8Yy8qvTVQIPfM8j9V3C9lL+JKzrqznJEE0rxQwr4qKnLcf9WDtiXaGAKTAy4Y6Z6mQCIfFRvtQ4TXlbYjbXOavz3vk4/GYYo/84T1F8wUO/Ylgf4OcKcemeKkd76wjiJpP75DVQcBQnne7NMgy5F3IiDksQqjpX+2s2vsD7sQwME3OyVxB4h6jDQzwpopjmpGr1onbMDXLtGBY2YDGbrJMC+snSa3MyCMBq0DMZah4xjzDGQrVgwKSVDnEqnm1s7PZ+MtBJf8BwYgZhM2MNxnMN7oD/GFMtxYr75zbumSHFuFhP2RhU3l1Cxkxd8KTNrPU9CDsCIeKKylxiyXRWPcMPWuGd2g3AF4Hpm7K8VWhPH3kJM1Qbti+UKbtSky90M8gvUFJS6zgfJ5Dq/kXZLTBhkEVNu2QPiygigLFK00oMyBEvd8DPNLeEGiFZbQ0Wtb35sMiQfA2pI0PgDvkYaMY7jJuFpas4fxIW35qhuTtefC8y9BXtpJdmI/f3lIu//LvZDpZUrIP3UBgK0Ad0iQllfjWaDIDD4mzW0XJ3XXJi5AWCJw7w5+RVDOhNteGrzdqaBbmi4W4Qhhtid6KQa0p+YqE=
  app: 9-1802-454f-17e44675
  on: master
