sudo: false
language: node_js
node_js:
  - 12.19.1
cache: yarn

install:
  - yarn install

script:
  - yarn run build

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app:
    master: hackernoon-react-ssr
  on: master
